---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_ENABLE_ADS: "true"
