# apiVersion: v1
# data:
#   .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjbVZrWTI5dE9tZG9jRjlYWnpKTVlqbDVZM2RKWjBWRVZYVlNSREZwUVRaUlMyZDVjR2x6TlhVelMzWXdUWEE9IgogICAgfQogIH0KfQo=
# kind: Secret
# metadata:
#   name: ghcr-secret
# type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  basicAuthUser: dXNlcm5hbWU=  # Base64-encoded username
  basicAuthPass: cGFzc3dvcmQ=  # Base64-encoded password
