name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'  # Only trigger when there are changes in the charts folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package Helm charts
        run: |
          mkdir -p docs
          for chart_dir in charts/*; do
            if [ -d "$chart_dir" ]; then
              helm package "$chart_dir" --destination docs
            fi
          done

      - name: Update Helm repository index
        run: |
          helm repo index docs --url https://kubikobot.github.io/helm-charts

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Update Helm chart repository" || echo "No changes to commit"
          git push
